#!/usr/bin/perl
use strict;
use warnings;
use WebminCore;

init_config();
header("Installing Timer");

print "<pre>\n";

system("cp /usr/local/system-maintenance/systemd/system-maintenance.service /etc/systemd/system/system-maintenance.service");
system("cp /usr/local/system-maintenance/systemd/system-maintenance.timer /etc/systemd/system/system-maintenance.timer");
system("systemctl daemon-reload");
system("systemctl enable --now system-maintenance.timer");

print "</pre>\n";
print "<p>Timer installed and enabled.</p>\n";

footer();
